# Generated by Django 3.1.7 on 2021-05-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
    ]
