# Generated by Django 3.1.7 on 2021-05-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_categorise'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.categorise'),
        ),
    ]
